live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

# lackluster theme begin
[colors.primary]
background = '#101010'

[colors.normal]
black = '#080808'
red = '#D70000'
green = '#789978'
# yellow = '#ffAA88'
yellow = '#f7bda6'
blue = '#7788AA'
# magenta = '#D7007D'
magenta = '#aa6666'
cyan = '#708090'
white = '#DEEEED'
# lackluster theme end

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_title = true
option_as_alt = "Both"
#startup_mode = "Maximized"
# opacity = 0.5

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 4
y = 4

[keyboard]
bindings = [
    { key = "C", mods = "Control", action = "Copy" },
    { key = "V", mods = "Control", action = "Paste"}
]
